apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: timber-frontend
        image: ghcr.io/lalyos/timber-frontend
        ports:
        - containerPort: 8080
        env:
          - {name: TIMBER_BACKEND_API_URL, value: "http://$(TIMBER_BACKEND_API_URL):8080"}
