name: Docker Image Build

on:
  push:
    branches: [ img-rep ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build backend --tag timber-backend:v1.0
